//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AutoCareDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Mantenimiento
    {
        public int Id { get; set; }
        public string TipoMantenimiento { get; set; }
        public System.DateTime Fecha { get; set; }
        public decimal Costo { get; set; }
        public int VehiculoId { get; set; }
        public string Observacion { get; set; }
        public string Taller { get; set; }
        public string Horario { get; set; }
    
        public virtual Vehiculo Vehiculo { get; set; }
    }
}
